### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by francoisschwarzentruber** [urholaukkarinen/algx#1]
Hello,
your program seems nice but it does not compile. I just run `cargo build` which seems the standard method to compile in Rust (I am not a specialist of Rust at all) and I get:

error[E0658]: `let...else` statements are unstable
   --> src/lib.rs:243:9
    |
243 | /         let Some(Step { node, backtracking }) = self.step_stack.pop() else {
244 | |             return None;
245 | |         };
    | |__________^
    |
    = note: see issue #87335 <https://github.com/rust-lang/rust/issues/87335> for more information

For more information about this error, try `rustc --explain E0658`.

It seems that `let...else`is not a standard feature.

Two ways to go:
- either the program has to be corrected to comply the standard
- or the README.md should explain what to do

Thank you!

**Comment by urholaukkarinen** [comment]
Which version of Rust do you have? The let-else syntax was added to stable Rust in version 1.65 (Nov. 3, 2022).

**Comment by urholaukkarinen** [comment]
Closing this. Feel free to re-open if the problem did not resolve
